language: android
jdk: oraclejdk8
dist: trusty

env:
  global:
  
android:
  components:
    
    - build-tools-25.0.2
    - android-29
  
  
  licenses:
  
  
before_install:
- chmod +x gradlew


before_script:
